# bracs_simclr.yaml
defaults:
  - _self_
  - augmentations: simclr_aug.yaml
  - wandb: null
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

name: "bracs-simclr"
method: "simclr"

backbone:
  name: "resnet50"
  kwargs:
    zero_init_residual: True

method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  temperature: 0.2

data:
  dataset: "custom"
  train_path: "/scratch/leuven/373/vsc37341/BRACS/train_flattened"
  val_path: null
  format: "image_folder"
  no_labels: True
  num_workers: 8

optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.6
  weight_decay: 1e-6
  classifier_lr: 0.1
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True

scheduler:
  name: "warmup_cosine"
  kwargs:
    warmup_epochs: 10

checkpoint:
  enabled: True
  dir: "checkpoints/simclr_bracs"
  frequency: 10

auto_resume:
  enabled: True

max_epochs: 200
devices: [0, 1]
accelerator: "gpu"
sync_batchnorm: True
strategy: "ddp"
precision: 16-mixed
